const availableflightAPI = [
  {
    flightid: "1",
    to: "KARACHI",
    from: "ISLAMABAD",
    airportto: "Jinnah International",
    airportfrom: "Islamabad International",
    time: "21:00",
    date: "31 JUL 2022",
    econseats: 30,
    busseat: 10,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 25,000",
    airline: "Airsial",
    logo: "",
  },
  {
    flightid: "2",
    to: "KARACHI",
    from: "DOHA",
    airportto: "Jinnah International",
    airportfrom: "Hamad International",
    time: "20:00",
    date: "7 JUL 2022",
    econseats: 60,
    busseat: 40,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 67,390",
    airline: "Airsial",
    logo: "",
  },
  {
    flightid: "3",
    to: "ISLAMABAD",
    from: "DUBAI",
    airportto: "Islamabad International",
    airportfrom: "Dubai International",
    time: "13:00",
    date: "1 OCT 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 98,300",
    airline: "Serene Air",
    logo: "",
  },
  {
    flightid: "4",
    to: "LAHORE",
    from: "ABU DHABI",
    airportto: "Allama Iqbal International",
    airportfrom: "Abu Dhabi International",
    time: "11:00",
    date: "3 AUG 2022",
    econseats: 127,
    busseat: 45,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 48,720",
    airline: "Serene Air",
    logo: "",
  },
  {
    flightid: "5",
    to: "LAHORE",
    from: "ABU DHABI",
    airportto: "Allama Iqbal International",
    airportfrom: "Abu Dhabi International",
    time: "12:00",
    date: "3 AUG 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 57,620",
    airline: "Qatar Airways",
    logo: "",
  },
  {
    flightid: "6",
    to: "LAHORE",
    from: "ABU DHABI",
    airportto: "Allama Iqbal International",
    airportfrom: "Abu Dhabi International",
    time: "12:00",
    date: "3 AUG 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 58,620",
    airline: "Emirates",
    logo: "",
  },
  {
    flightid: "7",
    to: "KARACHI",
    from: "ABU DHABI",
    airportto: "Jinnah International",
    airportfrom: "Abu Dhabi International",
    time: "16:00",
    date: "8 SEP 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 98,620",
    airline: "Airsial",
    logo: "",
  },
  {
    flightid: "8",
    to: "KARACHI",
    from: "ABU DHABI",
    airportto: "Jinnah International",
    airportfrom: "Abu Dhabi International",
    time: "16:00",
    date: "8 SEP 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 98,620",
    airline: "Airsial",
    logo: "",
  },
  {
    flightid: "9",
    to: "CALGARY",
    from: "KARACHI",
    airportto: "Calgary International",
    airportfrom: "Jinnah International",
    time: "16:00",
    date: "8 SEP 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 98,620",
    airline: "Pakistan International Airlines",
    logo: "",
  },
  {
    flightid: "10",
    to: "CALGARY",
    from: "NEW YORK",
    airportto: "Calgary International",
    airportfrom: "JFK International",
    time: "16:00",
    date: "16 JUL 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 144,620",
    airline: "American Airlines",
    logo: "",
  },
  {
    flightid: "11",
    to: "LAHORE",
    from: "ABU DHABI",
    airportto: "Allama Iqbal International",
    airportfrom: "Abu Dhabi International",
    time: "12:00",
    date: "4 AUG 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 45,870",
    airline: "Emirates",
    logo: "",
  },
];
export default availableflightAPI;
