const availableflightAPI = [
  {
    flightid: "1",
    to: "KARACHI",
    from: "ISLAMABAD",
    time: "21:00",
    date: "31 JAN 2022",
    seattype: "Business",
    price: "Rs. 25,000",
    airline: "Airsial",
  },
  {
    flightid: "2",
    to: "KARACHI",
    from: "LAHORE",
    time: "21:00",
    date: "31 JAN 2022",
    seattype: "Business",
    price: "Rs. 25,000",
    airline: "Airsial",
  },
  {
    flightid: "3",
    to: "ISLAMABAD",
    from: "DUBAI",
    time: "21:00",
    date: "31 JAN 2022",
    seattype: "Business",
    price: "Rs. 25,000",
    airline: "Airsial",
  },
  {
    flightid: "4",
    to: "MULTAN",
    from: "ISLAMABAD",
    time: "21:00",
    date: "31 JAN 2022",
    seattype: "Business",
    price: "Rs. 25,000",
    airline: "Airsial",
  },
  {
    flightid: "5",
    to: "LONDON",
    from: "KARACHI",
    time: "21:00",
    date: "31 JAN 2022",
    seattype: "Business",
    price: "Rs. 25,000",
    airline: "Airsial",
  },
  {
    flightid: "6",
    to: "MADRID",
    from: "MANCHESTER",
    time: "21:00",
    date: "31 JAN 2022",
    seattype: "Business",
    price: "Rs. 25,000",
    airline: "Airsial",
  },
  {
    flightid: "7",
    to: "TEHRAN",
    from: "SHARJAH",
    time: "21:00",
    date: "31 JAN 2022",
    seattype: "ECONOMY",
    price: "Rs. 122,000",
    airline: "IRAN AIRWAYS",
  },
];
export default availableflightAPI;
