const availableflightAPI = [
  {
    flightid: "1",
    to: "KARACHI",
    from: "ISLAMABAD",
    airport: "JINNAH INTERNATIONAL",
    time: "21:00",
    date: "31 JUL 2022",
    econseats: 30,
    busseat: 10,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 25,000",
    airline: "Airsial",
    logo: "",
  },
  {
    flightid: "2",
    to: "KARACHI",
    from: "DOHA",
    airport: "JINNAH INTERNATIONAL",
    time: "20:00",
    date: "7 JUL 2022",
    econseats: 60,
    busseat: 40,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 67,390",
    airline: "Airsial",
    logo: "",
  },
  {
    flightid: "3",
    to: "ISLAMABAD",
    from: "DUBAI",
    airport: "ISLAMABAD INTERNATIONAL",
    time: "13:00",
    date: "1 OCT 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 98,300",
    airline: "Serene Air",
    logo: "",
  },
  {
    flightid: "4",
    to: "LAHORE",
    from: "ABU DHABI",
    airport: "ALLAMA IQBAL INTERNATIONAL",
    time: "11:00",
    date: "3 AUG 2022",
    econseats: 127,
    busseat: 45,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 48,720",
    airline: "Emirates",
    logo: "",
  },
  {
    flightid: "5",
    to: "LAHORE",
    from: "ABU DHABI",
    airport: "ALLAMA IQBAL INTERNATIONAL",
    time: "12:00",
    date: "3 AUG 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 57,620",
    airline: "Qatar Airways",
    logo: "",
  },
  {
    flightid: "6",
    to: "LAHORE",
    from: "ABU DHABI",
    airport: "ALLAMA IQBAL INTERNATIONAL",
    time: "12:00",
    date: "3 AUG 2022",
    econseats: 300,
    busseat: 30,
    preconseat: 20,
    fclassseat: 30,
    price: "Rs. 58,620",
    airline: "Emirates",
    logo: "",
  },
];
export default availableflightAPI;
